export const STAT_GROUPS = [
  "Per Game",
  "Totals",
  "Advanced",
  "Per 100",
  "Play by Play",
  "Shooting",
] as const;

export const ACCOLADE_GROUPS = [
  "Championships",
  "All-League Teams",
  "Individual Awards",
] as const;

export type GroupName =
  | (typeof STAT_GROUPS)[number]
  | (typeof ACCOLADE_GROUPS)[number];

export type GroupsPreset = "stats" | "accolades" | "all" | "custom" | null;

// ----- Display stat groups for the SELECTED player -----
// Season columns (from nba_player_seasons.csv)
export const SEASON_PER_GAME_KEYS = [
  "mp_per_game",
  "pts_per_game",
  "orb_per_game",
  "drb_per_game",
  "trb_per_game",
  "ast_per_game",
  "stl_per_game",
  "blk_per_game",
  "fg_per_game",
  "fga_per_game",
  "fg_percent",
  "x2p_per_game",
  "x2pa_per_game",
  "x2p_percent",
  "x3p_per_game",
  "x3pa_per_game",
  "x3p_percent",
  "ft_per_game",
  "fta_per_game",
  "ft_percent",
  "e_fg_percent",
  "tov_per_game",
  "pf_per_game",
];

export const SEASON_TOTAL_KEYS = [
  "g",
  "gs",
  "mp",
  "pts",
  "orb",
  "drb",
  "trb",
  "ast",
  "stl",
  "blk",
  "fg",
  "fga",
  "x2p",
  "x2pa",
  "x3p",
  "x3pa",
  "ft",
  "fta",
  "tov",
  "pf",
  "trp_dbl",
];

export const SEASON_ADVANCED_KEYS = [
  "per",
  "ts_percent",
  "x3p_ar",
  "f_tr",
  "orb_percent",
  "drb_percent",
  "trb_percent",
  "ast_percent",
  "stl_percent",
  "blk_percent",
  "tov_percent",
  "usg_percent",
  "ows",
  "dws",
  "ws",
  "ws_48",
  "obpm",
  "dbpm",
  "bpm",
  "vorp",
];

export const SEASON_PER_100_KEYS = [
  "pts_per_100_poss",
  "orb_per_100_poss",
  "drb_per_100_poss",
  "trb_per_100_poss",
  "ast_per_100_poss",
  "stl_per_100_poss",
  "blk_per_100_poss",
  "fg_per_100_poss",
  "fga_per_100_poss",
  "x2p_per_100_poss",
  "x2pa_per_100_poss",
  "x3p_per_100_poss",
  "x3pa_per_100_poss",
  "ft_per_100_poss",
  "fta_per_100_poss",
  "tov_per_100_poss",
  "pf_per_100_poss",
  "o_rtg",
  "d_rtg",
];

export const SEASON_PLAY_BY_PLAY_KEYS = [
  "pg_percent",
  "sg_percent",
  "sf_percent",
  "pf_percent",
  "c_percent",
  "on_court_plus_minus_per_100_poss",
  "net_plus_minus_per_100_poss",
  "bad_pass_turnover",
  "lost_ball_turnover",
  "shooting_foul_committed",
  "offensive_foul_committed",
  "shooting_foul_drawn",
  "offensive_foul_drawn",
  "points_generated_by_assists",
  "and1",
  "fga_blocked",
];

export const SEASON_SHOOTING_KEYS = [
  "avg_dist_fga",
  "percent_fga_from_x2p_range",
  "percent_fga_from_x3p_range",
  "percent_fga_from_x0_3_range",
  "fg_percent_from_x0_3_range",
  "percent_fga_from_x3_10_range",
  "fg_percent_from_x3_10_range",
  "percent_fga_from_x10_16_range",
  "fg_percent_from_x10_16_range",
  "percent_fga_from_x16_3p_range",
  "fg_percent_from_x16_3p_range",
  "percent_corner_3s_of_3pa",
  "corner_3_point_percent",
  "num_heaves_attempted",
  "num_heaves_made",
  "percent_assisted_x2p_fg",
  "percent_assisted_x3p_fg",
  "percent_dunks_of_fga",
  "num_of_dunks",
];

export const SEASON_CHAMPIONSHIPS_KEYS = ["CHMP", "FMVP"];

export const SEASON_ALL_LEAGUE_TEAMS_KEYS = [
  "all_star",
  "all_nba_1T",
  "all_nba_2T",
  "all_nba_3T",
  "all_nba_ORV",
  "all_nba_share",
  "all_defense_1st",
  "all_defense_2nd",
  "all_defense_ORV",
  "all_defense_share",
  "all_rookie_1st",
  "all_rookie_2nd",
  "all_rookie_ORV",
  "all_rookie_share",
];

export const SEASON_INDIVIDUAL_AWARDS_KEYS = [
  "mvp_winner",
  "mvp_share",
  "dpoy_winner",
  "dpoy_share",
  "roy_winner",
  "roy_share",
  "mip_winner",
  "mip_share",
  "smoy_winner",
  "smoy_share",
  "clutch_poy_winner",
  "clutch_poy_share",
];

// Career columns (from nba_player_careers.csv)
export const CAREER_PER_GAME_KEYS = [
  "mp_per_game",
  "pts_per_game",
  "orb_per_game",
  "drb_per_game",
  "trb_per_game",
  "ast_per_game",
  "stl_per_game",
  "blk_per_game",
  "fg_per_game",
  "fga_per_game",
  "fg_percent",
  "x2p_per_game",
  "x2pa_per_game",
  "x2p_percent",
  "x3p_per_game",
  "x3pa_per_game",
  "x3p_percent",
  "ft_per_game",
  "fta_per_game",
  "ft_percent",
  "e_fg_percent",
  "tov_per_game",
  "pf_per_game",
];

export const CAREER_TOTAL_KEYS = [
  "career_g",
  "career_gs",
  "career_mp",
  "career_pts",
  "career_orb",
  "career_drb",
  "career_trb",
  "career_ast",
  "career_stl",
  "career_blk",
  "career_fg",
  "career_fga",
  "career_x2p",
  "career_x2pa",
  "career_x3p",
  "career_x3pa",
  "career_ft",
  "career_fta",
  "career_tov",
  "career_pf",
  "career_trp_dbl",
];

export const CAREER_ADVANCED_KEYS = [
  "career_per",
  "career_ts_percent",
  "career_x3p_ar",
  "career_f_tr",
  "career_orb_percent",
  "career_drb_percent",
  "career_trb_percent",
  "career_ast_percent",
  "career_stl_percent",
  "career_blk_percent",
  "career_tov_percent",
  "career_usg_percent",
  "career_ows",
  "career_dws",
  "career_ws",
  "career_ws_48",
  "career_obpm",
  "career_dbpm",
  "career_bpm",
  "career_vorp",
];

export const CAREER_PER_100_KEYS = [
  "career_pts_per_100_poss",
  "career_orb_per_100_poss",
  "career_drb_per_100_poss",
  "career_trb_per_100_poss",
  "career_ast_per_100_poss",
  "career_stl_per_100_poss",
  "career_blk_per_100_poss",
  "career_fg_per_100_poss",
  "career_fga_per_100_poss",
  "career_x2p_per_100_poss",
  "career_x2pa_per_100_poss",
  "career_x3p_per_100_poss",
  "career_x3pa_per_100_poss",
  "career_ft_per_100_poss",
  "career_fta_per_100_poss",
  "career_tov_per_100_poss",
  "career_pf_per_100_poss",
  "career_o_rtg",
  "career_d_rtg",
];

export const CAREER_PLAY_BY_PLAY_KEYS = [
  "career_pg_percent",
  "career_sg_percent",
  "career_sf_percent",
  "career_pf_percent",
  "career_c_percent",
  "career_on_court_plus_minus_per_100_poss",
  "career_net_plus_minus_per_100_poss",
  "career_bad_pass_turnover",
  "career_lost_ball_turnover",
  "career_shooting_foul_committed",
  "career_offensive_foul_committed",
  "career_shooting_foul_drawn",
  "career_offensive_foul_drawn",
  "career_points_generated_by_assists",
  "career_and1",
  "career_fga_blocked",
];

export const CAREER_SHOOTING_KEYS = [
  "career_avg_dist_fga",
  "career_percent_fga_from_x2p_range",
  "career_percent_fga_from_x3p_range",
  "career_percent_fga_from_x0_3_range",
  "career_fg_percent_from_x0_3_range",
  "career_percent_fga_from_x3_10_range",
  "career_fg_percent_from_x3_10_range",
  "career_percent_fga_from_x10_16_range",
  "career_fg_percent_from_x10_16_range",
  "career_percent_fga_from_x16_3p_range",
  "career_fg_percent_from_x16_3p_range",
  "career_percent_corner_3s_of_3pa",
  "career_corner_3_point_percent",
  "career_num_heaves_attempted",
  "career_num_heaves_made",
  "career_percent_assisted_x2p_fg",
  "career_percent_assisted_x3p_fg",
  "career_percent_dunks_of_fga",
  "career_num_of_dunks",
];

export const CAREER_CHAMPIONSHIPS_KEYS = [
  "career_CHMP_count",
  "career_FMVP_count",
];

export const CAREER_ALL_LEAGUE_TEAMS_KEYS = [
  "career_all_star_count",
  "career_all_nba_1T_count",
  "career_all_nba_2T_count",
  "career_all_nba_3T_count",
  "career_all_nba_ORV_count",
  "career_all_nba_share_mean",
  "career_all_defense_1st_count",
  "career_all_defense_2nd_count",
  "career_all_defense_ORV_count",
  "career_all_defense_share_mean",
  "career_all_rookie_1st_count",
  "career_all_rookie_2nd_count",
  "career_all_rookie_ORV_count",
  "career_all_rookie_share_mean",
];

export const CAREER_INDIVIDUAL_AWARDS_KEYS = [
  "career_mvp_winner_count",
  "career_mvp_share_mean",
  "career_dpoy_winner_count",
  "career_dpoy_share_mean",
  "career_roy_winner_count",
  "career_roy_share_sum",
  "career_mip_winner_count",
  "career_mip_share_mean",
  "career_smoy_winner_count",
  "career_smoy_share_mean",
  "career_clutch_poy_winner_count",
  "career_clutch_poy_share_mean",
];

// Optional: map raw stat keys to nicer display labels
export const STAT_LABELS: Record<string, string> = {
  // ---------- Season per-game ----------
  mp_per_game: "MPG",
  fg_per_game: "FGM_PG",
  fga_per_game: "FGA_PG",
  fg_percent: "FG%",
  x3p_per_game: "3PM_PG",
  x3pa_per_game: "3PA_PG",
  x3p_percent: "3P%",
  x2p_per_game: "2PM_PG",
  x2pa_per_game: "2PA_PG",
  x2p_percent: "2P%",
  e_fg_percent: "EFG%",
  ft_per_game: "FT_PG",
  fta_per_game: "FTA_PG",
  ft_percent: "FT%",
  orb_per_game: "ORPG",
  drb_per_game: "DRPG",
  trb_per_game: "RPG",
  ast_per_game: "APG",
  stl_per_game: "SPG",
  blk_per_game: "BPG",
  tov_per_game: "TOV_PG",
  pf_per_game: "PF_PG",
  pts_per_game: "PPG",

  // ---------- Season totals ----------
  g: "GP",
  gs: "GS",
  mp: "MP",
  fg: "FGM",
  fga: "FGA",
  x3p: "3PM",
  x3pa: "3PA",
  x2p: "2PM",
  x2pa: "2PA",
  ft: "FTM",
  fta: "FTA",
  orb: "ORB",
  drb: "DRB",
  trb: "REB",
  ast: "AST",
  stl: "STL",
  blk: "BLK",
  tov: "TOV",
  pf: "PF",
  pts: "PTS",
  trp_dbl: "TRP_DBL",

  // ---------- Season advanced ----------
  per: "PER",
  ts_percent: "TS%",
  x3p_ar: "3PAr",
  f_tr: "FTr",
  orb_percent: "ORB%",
  drb_percent: "DRB%",
  trb_percent: "REB%",
  ast_percent: "AST%",
  stl_percent: "STL%",
  blk_percent: "BLK%",
  tov_percent: "TOV%",
  usg_percent: "USG%",
  ows: "OWS",
  dws: "DWS",
  ws: "WS",
  ws_48: "WS/48",
  obpm: "OBPM",
  dbpm: "DBPM",
  bpm: "BPM",
  vorp: "VORP",

  // ---------- Season per-100 ----------
  fg_per_100_poss: "FGM/100",
  fga_per_100_poss: "FGA/100",
  x3p_per_100_poss: "3PM/100",
  x3pa_per_100_poss: "3PA/100",
  x2p_per_100_poss: "2PM/100",
  x2pa_per_100_poss: "2PA/100",
  ft_per_100_poss: "FTM/100",
  fta_per_100_poss: "FTA/100",
  orb_per_100_poss: "ORB/100",
  drb_per_100_poss: "DRB/100",
  trb_per_100_poss: "REB/100",
  ast_per_100_poss: "AST/100",
  stl_per_100_poss: "STL/100",
  blk_per_100_poss: "BLK/100",
  tov_per_100_poss: "TOV/100",
  pf_per_100_poss: "PF/100",
  pts_per_100_poss: "PTS/100",
  o_rtg: "O_RTG",
  d_rtg: "D_RTG",

  // ---------- Season play-by-play ----------
  pg_percent: "PG%",
  sg_percent: "SG%",
  sf_percent: "SF%",
  pf_percent: "PF%",
  c_percent: "C%",
  on_court_plus_minus_per_100_poss: "OnCourt+/-",
  net_plus_minus_per_100_poss: "Net+/-",
  bad_pass_turnover: "BadPass",
  lost_ball_turnover: "LostBall",
  shooting_foul_committed: "ShootFoulCommit",
  offensive_foul_committed: "OffFoulCommit",
  shooting_foul_drawn: "ShootFoulDraw",
  offensive_foul_drawn: "OffFoulDraw",
  points_generated_by_assists: "PGA",
  and1: "AND1",
  fga_blocked: "BLKD",

  // ---------- Season shooting ----------
  avg_dist_fga: "FGDist",
  percent_fga_from_x2p_range: "%FGA_2P",
  percent_fga_from_x0_3_range: "%FGA_0-3",
  percent_fga_from_x3_10_range: "FGA_%3-10",
  percent_fga_from_x10_16_range: "%FGA_10-16",
  percent_fga_from_x16_3p_range: "%FGA_16-3P",
  percent_fga_from_x3p_range: "%FGA_3P",
  fg_percent_from_x0_3_range: "FG%_0-3",
  fg_percent_from_x3_10_range: "FG%_3-10",
  fg_percent_from_x10_16_range: "FG%_10-16",
  fg_percent_from_x16_3p_range: "FG%_16-3P",
  percent_assisted_x2p_fg: "AST_FG%_2P",
  percent_assisted_x3p_fg: "AST_FG%_3P",
  percent_dunks_of_fga: "%FGA_DUNK",
  num_of_dunks: "DUNKS",
  percent_corner_3s_of_3pa: "%3PA_CRN",
  corner_3_point_percent: "3P%_CRN",
  num_heaves_attempted: "HEAVES_A",
  num_heaves_made: "HEAVES_M",

  // ---------- Season championships / accolades ----------
  CHMP: "CHMP",
  FMVP: "FMVP",
  all_star: "AS",
  all_defense_share: "DEF_S",
  all_nba_share: "NBA_S",
  all_rookie_share: "ROOK_S",
  all_defense_1st: "DEF_1",
  all_defense_2nd: "DEF_2",
  all_defense_ORV: "DEF_RV",
  all_nba_1T: "NBA_1",
  all_nba_2T: "NBA_2",
  all_nba_3T: "NBA_3",
  all_nba_ORV: "NBA_RV",
  all_rookie_1st: "ROOK_1",
  all_rookie_2nd: "ROOK_2",
  all_rookie_ORV: "ROOK_RV",

  // ---------- Season awards ----------
  mvp_winner: "MVP",
  mvp_share: "MVP_S",
  roy_winner: "ROY",
  roy_share: "ROY_S",
  smoy_winner: "SMOY",
  smoy_share: "SMOY_S",
  mip_winner: "MIP",
  mip_share: "MIP_S",
  dpoy_winner: "DPOY",
  dpoy_share: "DPOY_S",
  clutch_poy_winner: "CPOY",
  clutch_poy_share: "CPOY_S",

  // =====================================================
  // CAREER VERSIONS (mapped to the same display labels)
  // =====================================================

  // ---------- Career totals ----------
  career_g: "GP",
  career_gs: "GS",
  career_mp: "MP",
  career_fg: "FGM",
  career_fga: "FGA",
  career_x3p: "3PM",
  career_x3pa: "3PA",
  career_x2p: "2PM",
  career_x2pa: "2PA",
  career_ft: "FTM",
  career_fta: "FTA",
  career_orb: "ORB",
  career_drb: "DRB",
  career_trb: "REB",
  career_ast: "AST",
  career_stl: "STL",
  career_blk: "BLK",
  career_tov: "TOV",
  career_pf: "PF",
  career_pts: "PTS",
  career_trp_dbl: "TRP_DBL",

  // ---------- Career advanced ----------
  career_per: "PER",
  career_ts_percent: "TS%",
  career_x3p_ar: "3PAr",
  career_f_tr: "FTr",
  career_orb_percent: "ORB%",
  career_drb_percent: "DRB%",
  career_trb_percent: "REB%",
  career_ast_percent: "AST%",
  career_stl_percent: "STL%",
  career_blk_percent: "BLK%",
  career_tov_percent: "TOV%",
  career_usg_percent: "USG%",
  career_ows: "OWS",
  career_dws: "DWS",
  career_ws: "WS",
  career_ws_48: "WS/48",
  career_obpm: "OBPM",
  career_dbpm: "DBPM",
  career_bpm: "BPM",
  career_vorp: "VORP",

  // ---------- Career per-100 ----------
  career_fg_per_100_poss: "FGM/100",
  career_fga_per_100_poss: "FGA/100",
  career_x3p_per_100_poss: "3PM/100",
  career_x3pa_per_100_poss: "3PA/100",
  career_x2p_per_100_poss: "2PM/100",
  career_x2pa_per_100_poss: "2PA/100",
  career_ft_per_100_poss: "FTM/100",
  career_fta_per_100_poss: "FTA/100",
  career_orb_per_100_poss: "ORB/100",
  career_drb_per_100_poss: "DRB/100",
  career_trb_per_100_poss: "REB/100",
  career_ast_per_100_poss: "AST/100",
  career_stl_per_100_poss: "STL/100",
  career_blk_per_100_poss: "BLK/100",
  career_tov_per_100_poss: "TOV/100",
  career_pf_per_100_poss: "PF/100",
  career_pts_per_100_poss: "PTS/100",
  career_o_rtg: "O_RTG",
  career_d_rtg: "D_RTG",

  // ---------- Career play-by-play ----------
  career_pg_percent: "PG%",
  career_sg_percent: "SG%",
  career_sf_percent: "SF%",
  career_pf_percent: "PF%",
  career_c_percent: "C%",
  career_on_court_plus_minus_per_100_poss: "OnCourt+/-",
  career_net_plus_minus_per_100_poss: "Net+/-",
  career_bad_pass_turnover: "BadPass",
  career_lost_ball_turnover: "LostBall",
  career_shooting_foul_committed: "ShootFoulCommit",
  career_offensive_foul_committed: "OffFoulCommit",
  career_shooting_foul_drawn: "ShootFoulDraw",
  career_offensive_foul_drawn: "OffFoulDraw",
  career_points_generated_by_assists: "PGA",
  career_and1: "AND1",
  career_fga_blocked: "BLKD",

  // ---------- Career shooting ----------
  career_avg_dist_fga: "FGDist",
  career_percent_fga_from_x2p_range: "%FGA_2P",
  career_percent_fga_from_x0_3_range: "%FGA_0-3",
  career_percent_fga_from_x3_10_range: "FGA_%3-10",
  career_percent_fga_from_x10_16_range: "%FGA_10-16",
  career_percent_fga_from_x16_3p_range: "%FGA_16-3P",
  career_percent_fga_from_x3p_range: "%FGA_3P",
  career_fg_percent_from_x0_3_range: "FG%_0-3",
  career_fg_percent_from_x3_10_range: "FG%_3-10",
  career_fg_percent_from_x10_16_range: "FG%_10-16",
  career_fg_percent_from_x16_3p_range: "FG%_16-3P",
  career_percent_assisted_x2p_fg: "AST_FG%_2P",
  career_percent_assisted_x3p_fg: "AST_FG%_3P",
  career_percent_dunks_of_fga: "%FGA_DUNK",
  career_num_of_dunks: "DUNKS",
  career_percent_corner_3s_of_3pa: "%3PA_CRN",
  career_corner_3_point_percent: "3P%_CRN",
  career_num_heaves_attempted: "HEAVES_A",
  career_num_heaves_made: "HEAVES_M",

  // ---------- Career championships ----------
  career_CHMP_count: "CHMP",
  career_FMVP_count: "FMVP",

  // ---------- Career all-league teams ----------
  career_all_star_count: "AS",
  career_all_defense_share_mean: "DEF_S",
  career_all_nba_share_mean: "NBA_S",
  career_all_rookie_share_mean: "ROOK_S",
  career_all_defense_1st_count: "DEF_1",
  career_all_defense_2nd_count: "DEF_2",
  career_all_defense_ORV_count: "DEF_RV",
  career_all_nba_1T_count: "NBA_1",
  career_all_nba_2T_count: "NBA_2",
  career_all_nba_3T_count: "NBA_3",
  career_all_nba_ORV_count: "NBA_RV",
  career_all_rookie_1st_count: "ROOK_1",
  career_all_rookie_2nd_count: "ROOK_2",
  career_all_rookie_ORV_count: "ROOK_RV",

  // ---------- Career awards ----------
  career_mvp_winner_count: "MVP",
  career_mvp_share_mean: "MVP_S",
  career_roy_winner_count: "ROY",
  career_roy_share_sum: "ROY_S",
  career_smoy_winner_count: "SMOY",
  career_smoy_share_mean: "SMOY_S",
  career_mip_winner_count: "MIP",
  career_mip_share_mean: "MIP_S",
  career_dpoy_winner_count: "DPOY",
  career_dpoy_share_mean: "DPOY_S",
  career_clutch_poy_winner_count: "CPOY",
  career_clutch_poy_share_mean: "CPOY_S",
};

// Group config used for the SELECTED player stats panel
export type StatGroupConfig = {
  label: string;
  seasonKeys: string[];
  careerKeys: string[];
  alwaysShow?: boolean; // Per Game always shown; others only when "Show move" = true
};

export const STAT_GROUP_CONFIG: StatGroupConfig[] = [
  {
    label: "Per Game",
    seasonKeys: SEASON_PER_GAME_KEYS,
    careerKeys: CAREER_PER_GAME_KEYS,
    alwaysShow: true,
  },
  {
    label: "Totals",
    seasonKeys: SEASON_TOTAL_KEYS,
    careerKeys: CAREER_TOTAL_KEYS,
  },
  {
    label: "Advanced",
    seasonKeys: SEASON_ADVANCED_KEYS,
    careerKeys: CAREER_ADVANCED_KEYS,
  },
  {
    label: "Per 100",
    seasonKeys: SEASON_PER_100_KEYS,
    careerKeys: CAREER_PER_100_KEYS,
  },
  {
    label: "Play by Play",
    seasonKeys: SEASON_PLAY_BY_PLAY_KEYS,
    careerKeys: CAREER_PLAY_BY_PLAY_KEYS,
  },
  {
    label: "Shooting",
    seasonKeys: SEASON_SHOOTING_KEYS,
    careerKeys: CAREER_SHOOTING_KEYS,
  },
  {
    label: "Championships",
    seasonKeys: SEASON_CHAMPIONSHIPS_KEYS,
    careerKeys: CAREER_CHAMPIONSHIPS_KEYS,
  },
  {
    label: "All-League Teams",
    seasonKeys: SEASON_ALL_LEAGUE_TEAMS_KEYS,
    careerKeys: CAREER_ALL_LEAGUE_TEAMS_KEYS,
  },
  {
    label: "Individual Awards",
    seasonKeys: SEASON_INDIVIDUAL_AWARDS_KEYS,
    careerKeys: CAREER_INDIVIDUAL_AWARDS_KEYS,
  },
];
